### ISSUE TITLE
Add Rmarkdown reports

### ISSUE THREAD

**Issue by marijnbransen1998** [course-dprep/covid19_on_length_of_stay-team1-#10]
Deliverable:

Meaningful RMarkdown reports for (types of) raw data/input files are created, which allow potential users of the repository to understand the content of such files, and the definition of variables. The RMarkdown reports are properly formatted, rendered as HTML or PDF files, and feature information in a variety of modes (e.g., running text, tables, or figures). The rendered Markdown files are “publication-ready” - i.e., code that is not relevant to understanding the data or warning messages arehidden.

**Comment by KleinJonasUVT** [comment]
__Summary__ 
Rmarkdown files are only necessary for lines of code which need additional explanation, but not for things like loading in the data. The Rmarkdown file and the pdf file is therefore removed, a new file with only the code is added.
